-- Baseline schema for NTUST_Course_Monitor, generated from the live project
-- (eerlhmvwucnlbhemhvtz) on 2026-09-06 via information_schema / pg_catalog queries.
-- Ordered to run on an empty database; see 20260716011523_retain_system_logs.sql for the cron jobs.

create table if not exists public.email_test_requests (
  id bigint generated by default as identity not null,
  user_id uuid,
  email text not null,
  created_at timestamptz default timezone('utc'::text, now()),
  sent_at timestamptz,
  error text,
  constraint email_test_requests_pkey PRIMARY KEY (id),
  constraint email_test_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

create table if not exists public.monitored_courses (
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  course_code text not null,
  course_name text,
  semester text default '1142'::text,
  status text default 'pending'::text,
  auto_enroll boolean default false,
  current_enrolled text,
  last_check_time timestamptz,
  created_at timestamptz default timezone('utc'::text, now()),
  constraint monitored_courses_pkey PRIMARY KEY (id),
  constraint monitored_courses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

create table if not exists public.system_logs (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  type text default 'info'::text,
  message text,
  created_at timestamptz default timezone('utc'::text, now()),
  constraint system_logs_pkey PRIMARY KEY (id),
  constraint system_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

create table if not exists public.user_settings (
  user_id uuid not null,
  student_id text,
  student_password text,
  line_notify_token text,
  check_interval integer default 30,
  is_active boolean default false,
  updated_at timestamptz default timezone('utc'::text, now()),
  verify_ssl boolean default true,
  random_interval integer default 5,
  email_notify boolean default false,
  resend_api_key text,
  smtp_host text default 'smtp.gmail.com'::text,
  smtp_port integer default 587,
  smtp_username text,
  smtp_password text,
  enrollment_open_start text,
  enrollment_open_end text,
  enrollment_period text default 'A06'::text,
  is_encrypted boolean default false,
  proxy_enabled boolean default false,
  proxy_type text default 'socks5'::text,
  proxy_host text,
  proxy_port text,
  proxy_username text,
  proxy_password text,
  constraint user_settings_pkey PRIMARY KEY (user_id),
  constraint user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

create index if not exists idx_email_test_requests_pending ON public.email_test_requests USING btree (created_at) WHERE (sent_at IS NULL);
create index if not exists idx_email_test_requests_user_id ON public.email_test_requests USING btree (user_id);
create index if not exists idx_monitored_courses_user_id ON public.monitored_courses USING btree (user_id);
create index if not exists idx_system_logs_user_id ON public.system_logs USING btree (user_id);

alter table public.email_test_requests enable row level security;
alter table public.monitored_courses enable row level security;
alter table public.system_logs enable row level security;
alter table public.user_settings enable row level security;

create policy "Users can create own email test requests" on public.email_test_requests for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can read own email test requests" on public.email_test_requests for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can manage own courses" on public.monitored_courses for all to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can delete their own system_logs" on public.system_logs for delete to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can read own logs" on public.system_logs for select to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id));
create policy "Worker can insert logs" on public.system_logs for insert to authenticated
  with check ((( SELECT auth.uid() AS uid) = user_id));
create policy "Users can manage own settings" on public.user_settings for all to authenticated
  using ((( SELECT auth.uid() AS uid) = user_id))
  with check ((( SELECT auth.uid() AS uid) = user_id));

alter publication supabase_realtime add table public.monitored_courses;
alter publication supabase_realtime add table public.system_logs;
alter publication supabase_realtime add table public.user_settings;
